//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the D2Factory Xcode Templates so
//  you can apply D2Factory architecture to your iOS and Mac projects,
//  see http://d2factory.fr
//


import UIKit
import RxSwift

class ___VARIABLE_moduleName___ViewController: BaseViewController<___VARIABLE_moduleName___ViewModel> {

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func prepareStatesObserver() {
        self.sub(viewModel.observableData.asObservable().subscribe(onNext: { [weak self] uidata in
            self?.fillUI(uidata: uidata)
        }))
    }
    
    func fillUI(uidata: ___VARIABLE_moduleName___UIData) {
        if let errorMessage = uidata.errorMessage {
            self.showError(errorMessage)
        }
        toggleLoading(uidata.isLoading)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        viewModel.getData()
    }
    
    override func setup() {
        showBackButton()
    }

    
    func showError(_ message: String) {
        let alert = AlertView()
        self.present(alert.alert("Error", message: message), animated: true, completion: {
            self.viewModel.resetView()
        })
    }
    
    internal func toggleLoading(_ loading: Bool) {
    }
}

