//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the D2Factory Xcode Templates so
//  you can apply D2Factory architecture to your iOS and Mac projects,
//  see http://d2factory.fr
//

import Foundation

struct ___VARIABLE_moduleName___UIData {
    let errorMessage: String?
    let isLoading: Bool
    

    init(errorMessage: String? = nil, isLoading: Bool = false) {
        self.errorMessage = errorMessage
        self.isLoading = isLoading
    }
    
    func copy(errorMessage: String? = nil, isLoading: Bool = false) -> ___VARIABLE_moduleName___UIData {
        return ___VARIABLE_moduleName___UIData(errorMessage: errorMessage ?? self.errorMessage, isLoading: isLoading)
    }
}

