//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the D2Factory Xcode Templates so
//  you can apply D2Factory architecture to your iOS and Mac projects,
//  see http://d2factory.fr
//

import Foundation
import RxSwift

class ___VARIABLE_moduleName___UseCase {
    let observableData: Variable<___VARIABLE_moduleName___UIData> = Variable<___VARIABLE_moduleName___UIData>( ___VARIABLE_moduleName___UIData() )
    
    private let mapper: ___VARIABLE_moduleName___UIMapper = ___VARIABLE_moduleName___UIMapper()
    
    func request___VARIABLE_moduleName___Data() {
       
    }
}

class ___VARIABLE_moduleName___UIMapper {
    func map() -> ___VARIABLE_moduleName___UIData {

        return ___VARIABLE_moduleName___UIData()
    }
}
